language: node_js
os: linux
node_js: node

if: NOT commit_message =~ /Deploy .*/

install:
  - yarn install

script:
  - yarn monitor

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: master
