language: node_js
os: linux
node_js: node

if: NOT commit_message =~ /Deploy .*/

install:
  - yarn install

script:
  - yarn monitor

after_success:
  - |-
    # Send changes to Slack
    git diff report/rules.txt | jq -aRs . | read changes
    username="circumvention-monitor"
    payload="payload={\"username\": \"${username}\", \"text\": \"Circumvention report changes: ${changes}\"}"
    curl -X POST --data-urlencode "${payload}" ${SLACK_HOOK_URL}

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: master
